FROM python:3.10-slim

# タイムゾーン設定（対話モード回避）
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

# システムライブラリのインストール
RUN apt-get update && \
    apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリの設定
WORKDIR /app
COPY . /app

# 依存関係のインストール
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# アプリケーションの起動
CMD ["python", "main.py"]

#DOCKER実行コマンド例
# docker run -e DISPLAY=host.docker.internal:0 ` -v /tmp/.X11-unix:/tmp/.X11-unix ` --gpus all ` opencv-deer-detector